routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('courses', 'CourseController');

    Route::get('/', 'HomeController@index')->name('home');

    // Administrator
    Route::prefix('admin')->middleware(['admin'])->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'UserController@index')->name('users.index');
            Route::get('create', 'UserController@create')->name('users.create');
            Route::post('/', 'UserController@store')->name('users.store');
            Route::get('{user}', 'UserController@show')->name('users.show');
            Route::get('{user}/edit', 'UserController@edit')->name('users.edit');
            Route::patch('{user}', 'UserController@update')->name('users.update');
            Route::post('{user}/reactivate', 'UserController@reactivate')->name('users.reactivate');
            Route::delete('{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
        });
    });

    // Attendance
    Route::prefix('courses')->group(function () {
        Route::get('{course}/attendances/take', 'AttendanceController@create')->name('attendances.create');
        Route::put('{course}/attendances/edit', 'AttendanceController@saveToday')->name('attendances.save');
        Route::get('{course}/students/{student}/attendances/edit', 'AttendanceController@edit')->name('attendances.students.edit');
        Route::patch('{course}/students/{student}/attendances', 'AttendanceController@update')->name('attendances.students.update');
    });

    // Logged-in user profile
    Route::prefix('profiles/me')->group(function () {
        Route::get('edit', 'ProfileController@edit')->name('profiles.edit');
        Route::patch('/', 'ProfileController@update')->name('profiles.update');
    });

    Route::prefix('students')->group(function () {
        Route::get('/', 'StudentController@index')->name('students.index');
        Route::get('create', 'StudentController@create')->name('students.create');
        Route::post('/', 'StudentController@store')->name('students.store');
        // No students.show route.
        Route::get('{student}/edit', 'StudentController@edit')->name('students.edit');
        Route::patch('{student}', 'StudentController@update')->name('students.update');
        Route::post('{student}/reactivate', 'StudentController@reactivate')->name('students.reactivate');
        Route::delete('{student}/deactivate', 'StudentController@deactivate')->name('students.deactivate');
    });
});

app/Course.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Course
 * @package App
 */
class Course extends Model
{
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'monday' => 'boolean',
        'tuesday' => 'boolean',
        'wednesday' => 'boolean',
        'thursday' => 'boolean',
        'friday' => 'boolean',
        'expired' => 'boolean',
        'not_expired' => 'boolean',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'crn',
        'subject_code',
        'course_number',
        'section',
        'title',
        'start_date',
        'end_date',
        'start_time',
        'end_time',
        'timezone',
        'monday',
        'tuesday',
        'wednesday',
        'thursday',
        'friday',
        'course_term_id',
        'created_by',
        'updated_by',
    ];

    /**
     * Get the course attendance records associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Get the course term for the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function courseTerm()
    {
        return $this->belongsTo(CourseTerm::class);
    }

    /**
     * Get the students associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function students()
    {
        return $this->belongsToMany(Student::class);
    }

    /**
     * Get the instructors (users) associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function instructors()
    {
        return $this->belongsToMany(User::class);
    }

    /**
     * Get the course's code as a string.
     *
     * Format:
     *      [subject_code] [course_number]-[section]
     * Example:
     *      DIGM 101-001
     *
     * @return string
     */
    public function getCourseCodeAttribute()
    {
        return $this->subject_code . ' ' . $this->course_number . '-' . $this->section;
    }

    /**
     * Get the course's start time in 12-hour format with the meridian.
     *
     * @return string
     */
    public function getStartTime12Attribute()
    {
        return Carbon::parse($this->start_time)->format('h:i A');
    }

    /**
     * Get the course's end time in 12-hour format with the meridian.
     *
     * @return string
     */
    public function getEndTime12Attribute()
    {
        return Carbon::parse($this->end_time)->format('h:i A');
    }

    /**
     * Get the course's start time in 24-hour format without the seconds.
     *
     * @return string
     */
    public function getStartTime24Attribute()
    {
        return Carbon::parse($this->start_time)->format('H:i');
    }

    /**
     * Get the course's end time in 24-hour format without the seconds.
     *
     * @return string
     */
    public function getEndTime24Attribute()
    {
        return Carbon::parse($this->end_time)->format('H:i');
    }

    /**
     * Get a boolean if the course is past the end date.
     *
     * @return bool
     */
    public function getExpiredAttribute()
    {
        return Carbon::today()->timezone($this->timezone) > Carbon::parse($this->end_date);
    }

    /**
     * Get a boolean if the course is not past the end date.
     *
     * @return bool
     */
    public function getNotExpiredAttribute()
    {
        return Carbon::today()->timezone($this->timezone) <= Carbon::parse($this->end_date);
    }

    /**
     * Get the courses that have an end date before today, exclusively.
     * Query scope for chaining.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeExpired($query)
    {
        return $query->whereDate('end_date', '<', Carbon::today());
    }

    /**
     * Get the courses that have an end date at or after today.
     * Query scope for chaining.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNotExpired($query)
    {
        return $query->whereDate('end_date', '>=', Carbon::today());
    }
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Student
 *
 * @package App
 */
class Student extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'university_id',
        'email',
    ];

    /**
     * Get the courses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    /**
     * Get the course attendance statuses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Set the user to inactive and save it to the database.
     *
     * @return bool
     */
    public function deactivate()
    {
        $this->active = false;

        return $this->save();
    }

    /**
     * Set the user to active and save it to the database.
     *
     * @return bool
     */
    public function reactivate()
    {
        $this->active = true;

        return $this->save();
    }

    /**
     * Get the student's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Return a human-readable Yes/No string for the active flag.
     *
     * @return string
     */
    public function getIsActiveReadableAttribute()
    {
        return $this->active ? 'Yes' : 'No';
    }

    /**
     * Get the students that are active.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true);
    }
}

resources/views/attendances/manual.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel-heading">Take Attendance - {{ \Carbon\Carbon::today()->toFormattedDateString() }}</div>

        <div>
            @include('layouts.flash')

            <form id="attendance-form"
                  class="take-attendance-manual-form"
                  method="POST"
                  action="{{ route('attendances.save', ['course' => $course->id]) }}">
                @method('PUT')
                @csrf

                <table class="table">
                    <thead>
                        <tr class="table-header-row">
                            <th class="table-header-cell dash-attendance-student-first-name">First Name</th>
                            <th class="table-header-cell dash-attendance-student-last-name">Last Name</th>
                            <th class="table-header-cell dash-attendance-student-email">Email Address</th>
                            <th class="table-header-cell dash-actions">Status</th>
                        </tr>
                    </thead>

                    <tbody>
                        @if ($course->students->isNotEmpty())
                            @foreach ($course->students as $student)
                                <tr class="table-content-row">
                                    <td class="table-content-cell dash-attendance-student-first-name">{{ $student->first_name }}</td>

                                    <td class="table-content-cell dash-attendance-student-last-name">{{ $student->last_name }}</td>

                                    <td class="table-content-cell dash-attendance-student-email">{{ $student->email }}</td>

                                    <td class="table-content-cell">
                                        <div class="dash-actions">
                                            @foreach ($attendanceStatuses as $status)
                                                <div class="radio-container">
                                                    <input type="radio"
                                                           id="attendance-status-{{ $status->name }}-{{ $student->id }}"
                                                           class="radio radio-option"
                                                           name="attendances[{{ $student->id }}][status]"
                                                           value="{{ $status->id }}"
                                                           {{ (old('attendance[' . $student->id . '][status]') == $status->id) ||
                                                              ($student->courseAttendances->isEmpty() && $status->name == 'Absent') ||
                                                              ($student->courseAttendances->isNotEmpty() && $status->id == $student->courseAttendances->first()->attendance_status_id)
                                                                ? 'checked'
                                                                : '' }}>

                                                    <label for="attendance-status-{{ $status->name }}-{{ $student->id }}">{{ $status->name }}</label>
                                                </div>
                                            @endforeach

                                            <div class="checkbox-with-label-container">
                                                <input type="checkbox"
                                                       id="attendance-excused-{{ $student->id }}"
                                                       class="checkbox"
                                                       name="attendances[{{ $student->id }}][excused]"
                                                       value="1"
                                                       {{ old('attendance[' . $student->id . '][excused]') == 1 ||
                                                          ($student->courseAttendances->isNotEmpty() && $student->courseAttendances->first()->excused == 1)
                                                            ? 'checked'
                                                            : '' }}>

                                                <label for="attendance-excused-{{ $student->id }}">Excused</label>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr class="table-content-row">
                                <td class="table-content-cell" colspan="4">There are no students registered.</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </form>

            <div class="form-submit-buttons">
                <button type="submit" form="attendance-form" class="btn btn-primary btn-submit" onclick="window.confirm('Are you sure you would like to submit today\'s attendance?');">Save</button>
            </div>
        </div>
    </div>
@endsection

resources/views/attendances/student_list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel-heading">
            <p>Attendance for {{ $student->full_name }}</p>
            <p>{{ $course->course_code }}</p>
        </div>

        <div>
            @include('layouts.flash')

            <form id="attendance-form"
                  class="attendance-student-update-form"
                  method="POST"
                  action="{{ route('attendances.students.update', ['course' => $course->id, 'student' => $student->id]) }}">
                @method('PATCH')
                @csrf

                <table class="table">
                    <thead>
                        <tr class="table-header-row">
                            <th class="table-header-cell dash-attendance-student-date">Date</th>
                            <th class="table-header-cell dash-attendance-student-day-of-week">Day of Week</th>
                            <th class="table-header-cell dash-actions">Status</th>
                            <th class="table-header-cell dash-attendance-student-note">Note</th>
                        </tr>
                    </thead>

                    <tbody>
                        @if ($student->courseAttendances->isNotEmpty())
                            @foreach ($student->courseAttendances as $attendance)
                                <tr class="table-content-row">
                                    <td class="table-content-cell dash-attendance-student-date">{{ $attendance->getCreatedAtDateTime12($course->timezone) }}</td>

                                    <td class="table-content-cell dash-attendance-student-day-of-week">{{ $attendance->getCreatedAtDayOfWeek($course->timezone) }}</td>

                                    <td class="table-content-cell">
                                        <div class="dash-actions">
                                            @foreach ($attendanceStatuses as $status)
                                                <div class="radio-container">
                                                    <input type="radio"
                                                           id="attendance-status-{{ $status->name }}-{{ $attendance->id }}"
                                                           class="radio radio-option"
                                                           name="attendances[{{ $attendance->id }}][status]"
                                                           value="{{ $status->id }}"
                                                           {{ (old('attendances[' . $attendance->id . '][status]') == $status->id) ||
                                                              ($status->id == $attendance->attendance_status_id)
                                                                ? 'checked'
                                                                : '' }}>

                                                    <label for="attendance-status-{{ $status->name }}-{{ $attendance->id }}">{{ $status->name }}</label>

                                                    @if ($errors->has('attendances[' . $attendance->id . '][status]'))
                                                        <span class="help-block">
                                                            <strong>{{ $errors->first('attendances[' . $attendance->id . '][status]') }}</strong>
                                                        </span>
                                                    @endif
                                                </div>
                                            @endforeach

                                            <div class="checkbox-with-label-container">
                                                <input type="checkbox"
                                                       id="attendance-excused-{{ $attendance->id }}"
                                                       class="checkbox"
                                                       name="attendances[{{ $attendance->id }}][excused]"
                                                       value="1"
                                                       {{ old('attendances[' . $attendance->id . '][excused]') == 1 ||
                                                          ($attendance->excused == 1)
                                                            ? 'checked'
                                                            : '' }}>

                                                <label for="attendance-excused-{{ $attendance->id }}">Excused</label>

                                                @if ($errors->has('attendances[' . $attendance->id . '][excused]'))
                                                    <span class="help-block">
                                                        <strong>{{ $errors->first('attendances[' . $attendance->id . '][excused]') }}</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                    </td>

                                    <td class="table-content-cell dash-attendance-student-note">
                                        <textarea id="attendance-note-{{ $attendance->id }}"
                                                  class="textarea form-control"
                                                  name="attendances[{{ $attendance->id }}][note]"
                                                  placeholder="What is the reason for the status?"
                                                  cols="30"
                                                  rows="2">{{ old('attendances[' . $attendance->id . '][note]', $attendance->note) }}</textarea>

                                        @if ($errors->has('attendances[' . $attendance->id . '][note]'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('attendances[' . $attendance->id . '][note]') }}</strong>
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr class="table-content-row">
                                <td class="table-content-cell" colspan="3">There are no attendance records.</td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </form>

            <div class="form-submit-buttons">
                <a class="btn btn-primary btn-link btn-submit" href="{{ route('courses.show', ['course' => $course->id]) }}">
                    Cancel
                </a>

                <button type="submit" form="attendance-form" class="btn btn-primary btn-submit">Save</button>
            </div>
        </div>
    </div>
@endsection