routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('courses', 'CourseController');

    Route::get('/', 'HomeController@index')->name('home');

    // Administrator
    Route::prefix('admin')->middleware(['admin'])->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'UserController@index')->name('users.index');
            Route::get('create', 'UserController@create')->name('users.create');
            Route::post('/', 'UserController@store')->name('users.store');
            Route::get('{user}', 'UserController@show')->name('users.show');
            Route::get('{user}/edit', 'UserController@edit')->name('users.edit');
            Route::patch('{user}', 'UserController@update')->name('users.update');
            Route::post('{user}/reactivate', 'UserController@reactivate')->name('users.reactivate');
            Route::delete('{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
        });
    });

    // Attendance
    Route::prefix('courses')->group(function () {
        Route::get('{course}/attendances/take', 'AttendanceController@create')->name('attendances.create');
        Route::put('{course}/attendances/edit', 'AttendanceController@saveToday')->name('attendances.save');
        Route::get('{course}/students/{student}/attendances/edit', 'AttendanceController@edit')->name('attendances.students.edit');
        Route::patch('{course}/students/{student}/attendances', 'AttendanceController@update')->name('attendances.students.update');
    });

    // Logged-in user profile
    Route::prefix('profiles/me')->group(function () {
        Route::get('edit', 'ProfileController@edit')->name('profiles.edit');
        Route::patch('/', 'ProfileController@update')->name('profiles.update');
    });

    Route::prefix('students')->group(function () {
        Route::get('/', 'StudentController@index')->name('students.index');
        Route::get('create', 'StudentController@create')->name('students.create');
        Route::post('/', 'StudentController@store')->name('students.store');
        // No students.show route.
        Route::get('{student}/edit', 'StudentController@edit')->name('students.edit');
        Route::patch('{student}', 'StudentController@update')->name('students.update');
        Route::post('{student}/reactivate', 'StudentController@reactivate')->name('students.reactivate');
        Route::delete('{student}/deactivate', 'StudentController@deactivate')->name('students.deactivate');
    });
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Student
 *
 * @package App
 */
class Student extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'university_id',
        'email',
    ];

    /**
     * Get the courses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    /**
     * Get the course attendance statuses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Set the user to inactive and save it to the database.
     *
     * @return bool
     */
    public function deactivate()
    {
        $this->active = false;

        return $this->save();
    }

    /**
     * Set the user to active and save it to the database.
     *
     * @return bool
     */
    public function reactivate()
    {
        $this->active = true;

        return $this->save();
    }

    /**
     * Get the student's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Return a human-readable Yes/No string for the active flag.
     *
     * @return string
     */
    public function getIsActiveReadableAttribute()
    {
        return $this->active ? 'Yes' : 'No';
    }

    /**
     * Get the students that are active.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentRequest;
use App\Student;

/**
 * Class StudentController
 *
 * @package App\Http\Controllers
 */
class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::orderBy('active', 'desc')
            ->orderBy('last_name')
            ->orderBy('first_name')
            ->get();

        return view('students.list', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StudentRequest  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StudentRequest $request)
    {
        $studentData = [
            'first_name' => request('first_name'),
            'last_name' => request('last_name'),
            'university_id' => request('university_id'),
            'email' => request('email'),
        ];

        if (Student::create($studentData)) {
            session()->flash('success', 'Student has been successfully added');

            return redirect(route('students.index'));
        } else {
            session()->flash('error', 'Unable to add student');

            return redirect(route('students.create'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);

        if (is_null($student)) {
            session()->flash('error', 'Student could not be found');

            return back();
        }

        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  StudentRequest  $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(StudentRequest $request, $id)
    {
        $student = Student::find($id);

        if (is_null($student)) {
            session()->flash('error', 'Student could not be found');

            return back();
        }

        $student->first_name = request('first_name');
        $student->last_name = request('last_name');
        $student->university_id = request('university_id');
        $student->email = request('email');

        if ($student->save()) {
            session()->flash('success', 'Student has been successfully updated');

            return redirect(route('students.index'));
        } else {
            session()->flash('error', 'Unable to update student');

            return redirect(route('students.edit', ['student' => $student->id]));
        }
    }

    /**
     * Deactivate the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function deactivate($id)
    {
        /** @var Student $student */
        $student = Student::find($id);

        if (is_null($student)) {
            session()->flash('error', 'Student could not be found');

            return redirect(route('students.index'));
        }

        if ($student->deactivate()) {
            session()->flash('success', 'Student has been successfully deactivated');
        } else {
            session()->flash('error', 'Unable to deactivate student');
        }

        return redirect(route('students.index'));
    }

    /**
     * Reactivate the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function reactivate($id)
    {
        /** @var Student $student */
        $student = Student::find($id);

        if (is_null($student)) {
            session()->flash('error', 'Student could not be found');

            return redirect(route('students.index'));
        }

        if ($student->reactivate()) {
            session()->flash('success', 'Student has been successfully reactivated');
        } else {
            session()->flash('error', 'Unable to reactivate student');
        }

        return redirect(route('students.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);

        if (is_null($student)) {
            session()->flash('error', 'Student could not be found');

            return redirect(route('students.index'));
        }

        if ($student->delete()) {
            session()->flash('success', 'Student has been successfully removed');
        } else {
            session()->flash('error', 'Unable to remove student');
        }

        return redirect(route('students.index'));
    }
}

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')
@php
    $isNewStudent = !isset($student);
@endphp

<div class="container">
    <div class="panel-heading">
        @if ($isNewStudent)
            Create Student
        @else
            Edit Student
        @endif
    </div>

    <div>
        @include('layouts.flash')

        <form class="standard-form"
              method="POST"
              action="{{ route(
                'students.' . ($isNewStudent ? 'store' : 'update'),
                $isNewStudent ? [] : ['student' => $student->id]
              ) }}">
            @csrf
            @if (!$isNewStudent)
                @method('PATCH')
            @endif

            <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                <label for="first-name" class="control-label required">First Name</label>

                <div class="form-field">
                    <input type="text"
                           id="first-name"
                           class="form-control"
                           name="first_name"
                           value="{{ old('first_name', $isNewStudent ? '' : $student->first_name) }}"
                           placeholder="John"
                           required
                           autofocus>

                    @if ($errors->has('first_name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('first_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                <label for="last-name" class="control-label required">Last Name</label>

                <div class="form-field">
                    <input type="text"
                           id="last-name"
                           class="form-control"
                           name="last_name"
                           value="{{ old('last_name', $isNewStudent ? '' : $student->last_name) }}"
                           placeholder="Smith"
                           required
                           autofocus>

                    @if ($errors->has('last_name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('last_name') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('university_id') ? ' has-error' : '' }}">
                <label for="university-id" class="control-label required">Student ID</label>

                <div class="form-field">
                    <input type="text"
                           id="university-id"
                           class="form-control"
                           name="university_id"
                           value="{{ old('university_id', $isNewStudent ? '' : $student->university_id) }}"
                           placeholder="12345678"
                           required>

                    @if ($errors->has('university_id'))
                        <span class="help-block">
                            <strong>{{ $errors->first('university_id') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                <label for="email" class="control-label required">Student Email</label>

                <div class="form-field">
                    <input type="email"
                           id="email"
                           class="form-control"
                           name="email"
                           value="{{ old('email', $isNewStudent ? '' : $student->email) }}"
                           placeholder="example@example.com"
                           required>

                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
            </div>

            <div class="form-submit-buttons">
                <a class="btn btn-primary btn-link btn-submit" href="{{ route('students.index') }}">
                    Cancel
                </a>

                <button type="submit" class="btn btn-primary btn-submit">
                    @if ($isNewStudent)
                        Create
                    @else
                        Update
                    @endif
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/students/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel-heading">Students</div>

        <div>
            @include('layouts.flash')

            <table class="table">
                <thead>
                    <tr class="table-header-row">
                        <th class="table-header-cell dash-student-first-name">First Name</th>
                        <th class="table-header-cell dash-student-last-name">Last Name</th>
                        <th class="table-header-cell dash-student-email">Email Address</th>
                        <th class="table-header-cell dash-student-active">Active</th>
                        <th class="table-header-cell dash-actions">
                            <a href="{{ route('students.create') }}" class="btn btn-primary btn-link">Add Student</a>
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @if ($students->isNotEmpty())
                        @foreach ($students as $student)
                            <tr class="table-content-row">
                                <td class="table-content-cell dash-student-first-name">{{ $student->first_name }}</td>

                                <td class="table-content-cell dash-student-last-name">{{ $student->last_name }}</td>

                                <td class="table-content-cell dash-student-email">{{ $student->email }}</td>

                                <td class="table-content-cell dash-student-active">{{ $student->is_active_readable }}</td>

                                <td class="table-content-cell dash-actions">
                                    @if ($student->active)
                                        <form class="inline-form" method="POST" action="{{ route('students.deactivate', ['student' => $student->id]) }}">
                                            @method('DELETE')
                                            @csrf

                                            <button type="submit" class="btn btn-red btn-submit" onclick="window.confirm('Are you sure you want to remove {{ $student->full_name }}?');">Deactivate</button>
                                        </form>
                                    @else
                                        <form class="inline-form" method="POST" action="{{ route('students.reactivate', ['student' => $student->id]) }}">
                                            @csrf

                                            <button type="submit" class="btn btn-red btn-submit" onclick="window.confirm('Are you sure you want to activate {{ $student->full_name }}?');">Activate</button>
                                        </form>
                                    @endif

                                    <a href="{{ route('students.edit', ['student' => $student->id]) }}" class="btn btn-primary btn-link">Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr class="table-content-row">
                            <td class="table-content-cell" colspan="4">There are no students registered.</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection