routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('courses', 'CourseController');

    Route::get('/', 'HomeController@index')->name('home');

    // Administrator
    Route::prefix('admin')->middleware(['admin'])->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'UserController@index')->name('users.index');
            Route::get('create', 'UserController@create')->name('users.create');
            Route::post('/', 'UserController@store')->name('users.store');
            Route::get('{user}', 'UserController@show')->name('users.show');
            Route::get('{user}/edit', 'UserController@edit')->name('users.edit');
            Route::patch('{user}', 'UserController@update')->name('users.update');
            Route::post('{user}/reactivate', 'UserController@reactivate')->name('users.reactivate');
            Route::delete('{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
        });
    });

    // Attendance
    Route::prefix('courses')->group(function () {
        Route::get('{course}/attendances/take', 'AttendanceController@create')->name('attendances.create');
        Route::put('{course}/attendances/edit', 'AttendanceController@saveToday')->name('attendances.save');
        Route::get('{course}/students/{student}/attendances/edit', 'AttendanceController@edit')->name('attendances.students.edit');
        Route::patch('{course}/students/{student}/attendances', 'AttendanceController@update')->name('attendances.students.update');
    });

    // Logged-in user profile
    Route::prefix('profiles/me')->group(function () {
        Route::get('edit', 'ProfileController@edit')->name('profiles.edit');
        Route::patch('/', 'ProfileController@update')->name('profiles.update');
    });

    Route::prefix('students')->group(function () {
        Route::get('/', 'StudentController@index')->name('students.index');
        Route::get('create', 'StudentController@create')->name('students.create');
        Route::post('/', 'StudentController@store')->name('students.store');
        // No students.show route.
        Route::get('{student}/edit', 'StudentController@edit')->name('students.edit');
        Route::patch('{student}', 'StudentController@update')->name('students.update');
        Route::post('{student}/reactivate', 'StudentController@reactivate')->name('students.reactivate');
        Route::delete('{student}/deactivate', 'StudentController@deactivate')->name('students.deactivate');
    });
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Student
 *
 * @package App
 */
class Student extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'university_id',
        'email',
    ];

    /**
     * Get the courses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    /**
     * Get the course attendance statuses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Set the user to inactive and save it to the database.
     *
     * @return bool
     */
    public function deactivate()
    {
        $this->active = false;

        return $this->save();
    }

    /**
     * Set the user to active and save it to the database.
     *
     * @return bool
     */
    public function reactivate()
    {
        $this->active = true;

        return $this->save();
    }

    /**
     * Get the student's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Return a human-readable Yes/No string for the active flag.
     *
     * @return string
     */
    public function getIsActiveReadableAttribute()
    {
        return $this->active ? 'Yes' : 'No';
    }

    /**
     * Get the students that are active.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'DIGM Attendance') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/reset.css') }}" rel="stylesheet">
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app" class="app-grid">
        <header class="app-header">
            @include('layouts.nav')
        </header>

        <aside class="start sidebar">
            @yield('sidebar-left')
        </aside>

        <div class="center content">
            @yield('content')
        </div>

        <aside class="end sidebar">
            @yield('sidebar-right')
        </aside>

        <footer class="app-footer">
            @yield('footer')

            <section class="footer-info">© {{ \Carbon\Carbon::now()->year }}</section>
        </footer>
    </div>

    <!-- Scripts -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/flash.blade.php
@if (session('info'))
    <div class="alert alert-info" role="alert">
        {{ session('info') }}
    </div>
@elseif (session('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@elseif (session('warning'))
    <div class="alert alert-warning" role="alert">
        {{ session('warning') }}
    </div>
@elseif (session('error'))
    <div class="alert alert-danger" role="alert">
        {{ session('error') }}
    </div>
@endif

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-static-top">
    @auth
    <!-- Left Side Of Navbar -->
    <ul class="navbar-nav">
        <li class="navbar-link-item navbar-brand-container">
            <!-- Branding Image -->
            <a href="{{ route('home') }}" class="navbar-brand navbar-link">
                <img src="{{ asset('img/westphal-logo.png') }}" alt="Westphal Logo" class="navbar-logo">
            </a>
        </li>
    </ul>

    <!-- Right Side Of Navbar -->
    <ul class="navbar-nav navbar-right">
        <li class="navbar-link-item navbar-text-container">
            <a href="{{ route('courses.index') }}" class="navbar-link navbar-text">
                Courses
            </a>
        </li>

        <li class="navbar-link-item navbar-text-container">
            <a href="{{ route('students.index') }}" class="navbar-link navbar-text">
                Students
            </a>
        </li>

        @if (auth()->user()->is_admin)
            <li class="navbar-link-item navbar-text-container">
                <a href="{{ route('users.index') }}" class="navbar-link navbar-text">
                    Admin
                </a>
            </li>
        @endif

        <li class="navbar-link-item navbar-text-container">
            <a href="{{ route('profiles.edit') }}" class="navbar-link navbar-text">
                {{ auth()->user()->full_name }}
            </a>
        </li>

        <li class="navbar-link-item">
            <button form="logout-form"
                    class="navbar-link btn btn-primary">
                Logout
            </button>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>
    @endauth
</nav>