routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::resource('courses', 'CourseController');

    Route::get('/', 'HomeController@index')->name('home');

    // Administrator
    Route::prefix('admin')->middleware(['admin'])->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'UserController@index')->name('users.index');
            Route::get('create', 'UserController@create')->name('users.create');
            Route::post('/', 'UserController@store')->name('users.store');
            Route::get('{user}', 'UserController@show')->name('users.show');
            Route::get('{user}/edit', 'UserController@edit')->name('users.edit');
            Route::patch('{user}', 'UserController@update')->name('users.update');
            Route::post('{user}/reactivate', 'UserController@reactivate')->name('users.reactivate');
            Route::delete('{user}/deactivate', 'UserController@deactivate')->name('users.deactivate');
        });
    });

    // Attendance
    Route::prefix('courses')->group(function () {
        Route::get('{course}/attendances/take', 'AttendanceController@create')->name('attendances.create');
        Route::put('{course}/attendances/edit', 'AttendanceController@saveToday')->name('attendances.save');
        Route::get('{course}/students/{student}/attendances/edit', 'AttendanceController@edit')->name('attendances.students.edit');
        Route::patch('{course}/students/{student}/attendances', 'AttendanceController@update')->name('attendances.students.update');
    });

    // Logged-in user profile
    Route::prefix('profiles/me')->group(function () {
        Route::get('edit', 'ProfileController@edit')->name('profiles.edit');
        Route::patch('/', 'ProfileController@update')->name('profiles.update');
    });

    Route::prefix('students')->group(function () {
        Route::get('/', 'StudentController@index')->name('students.index');
        Route::get('create', 'StudentController@create')->name('students.create');
        Route::post('/', 'StudentController@store')->name('students.store');
        // No students.show route.
        Route::get('{student}/edit', 'StudentController@edit')->name('students.edit');
        Route::patch('{student}', 'StudentController@update')->name('students.update');
        Route::post('{student}/reactivate', 'StudentController@reactivate')->name('students.reactivate');
        Route::delete('{student}/deactivate', 'StudentController@deactivate')->name('students.deactivate');
    });
});

app/Course.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Course
 * @package App
 */
class Course extends Model
{
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'monday' => 'boolean',
        'tuesday' => 'boolean',
        'wednesday' => 'boolean',
        'thursday' => 'boolean',
        'friday' => 'boolean',
        'expired' => 'boolean',
        'not_expired' => 'boolean',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'crn',
        'subject_code',
        'course_number',
        'section',
        'title',
        'start_date',
        'end_date',
        'start_time',
        'end_time',
        'timezone',
        'monday',
        'tuesday',
        'wednesday',
        'thursday',
        'friday',
        'course_term_id',
        'created_by',
        'updated_by',
    ];

    /**
     * Get the course attendance records associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Get the course term for the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function courseTerm()
    {
        return $this->belongsTo(CourseTerm::class);
    }

    /**
     * Get the students associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function students()
    {
        return $this->belongsToMany(Student::class);
    }

    /**
     * Get the instructors (users) associated with the course.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function instructors()
    {
        return $this->belongsToMany(User::class);
    }

    /**
     * Get the course's code as a string.
     *
     * Format:
     *      [subject_code] [course_number]-[section]
     * Example:
     *      DIGM 101-001
     *
     * @return string
     */
    public function getCourseCodeAttribute()
    {
        return $this->subject_code . ' ' . $this->course_number . '-' . $this->section;
    }

    /**
     * Get the course's start time in 12-hour format with the meridian.
     *
     * @return string
     */
    public function getStartTime12Attribute()
    {
        return Carbon::parse($this->start_time)->format('h:i A');
    }

    /**
     * Get the course's end time in 12-hour format with the meridian.
     *
     * @return string
     */
    public function getEndTime12Attribute()
    {
        return Carbon::parse($this->end_time)->format('h:i A');
    }

    /**
     * Get the course's start time in 24-hour format without the seconds.
     *
     * @return string
     */
    public function getStartTime24Attribute()
    {
        return Carbon::parse($this->start_time)->format('H:i');
    }

    /**
     * Get the course's end time in 24-hour format without the seconds.
     *
     * @return string
     */
    public function getEndTime24Attribute()
    {
        return Carbon::parse($this->end_time)->format('H:i');
    }

    /**
     * Get a boolean if the course is past the end date.
     *
     * @return bool
     */
    public function getExpiredAttribute()
    {
        return Carbon::today()->timezone($this->timezone) > Carbon::parse($this->end_date);
    }

    /**
     * Get a boolean if the course is not past the end date.
     *
     * @return bool
     */
    public function getNotExpiredAttribute()
    {
        return Carbon::today()->timezone($this->timezone) <= Carbon::parse($this->end_date);
    }

    /**
     * Get the courses that have an end date before today, exclusively.
     * Query scope for chaining.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeExpired($query)
    {
        return $query->whereDate('end_date', '<', Carbon::today());
    }

    /**
     * Get the courses that have an end date at or after today.
     * Query scope for chaining.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNotExpired($query)
    {
        return $query->whereDate('end_date', '>=', Carbon::today());
    }
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Student
 *
 * @package App
 */
class Student extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'university_id',
        'email',
    ];

    /**
     * Get the courses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    /**
     * Get the course attendance statuses associated with a student.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function courseAttendances()
    {
        return $this->hasMany(CourseAttendance::class);
    }

    /**
     * Set the user to inactive and save it to the database.
     *
     * @return bool
     */
    public function deactivate()
    {
        $this->active = false;

        return $this->save();
    }

    /**
     * Set the user to active and save it to the database.
     *
     * @return bool
     */
    public function reactivate()
    {
        $this->active = true;

        return $this->save();
    }

    /**
     * Get the student's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * Return a human-readable Yes/No string for the active flag.
     *
     * @return string
     */
    public function getIsActiveReadableAttribute()
    {
        return $this->active ? 'Yes' : 'No';
    }

    /**
     * Get the students that are active.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('active', true);
    }
}

resources/views/courses/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="panel-heading">
        <p>{{ $course->course_code }}</p>
        <p>{{ $course->title }}</p>
    </div>

    @include('layouts.flash')

    <div class="course-grid">
        <table class="table course-details start">
            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">CRN:</td>
                <td class="table-content-cell course-detail-cell"> {{ $course->crn }}</td>
            </tr>

            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">Start Date:</td>
                <td class="table-content-cell course-detail-cell">{{ $course->start_date }}</td>
            </tr>

            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">End Date:</td>
                <td class="table-content-cell course-detail-cell">{{ $course->end_date }}</td>
            </tr>

            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">Start Time:</td>
                <td class="table-content-cell course-detail-cell">{{ $course->start_time_12 }}</td>
            </tr>

            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">End Time:</td>
                <td class="table-content-cell course-detail-cell">{{ $course->end_time_12 }}</td>
            </tr>

            <tr class="table-content-row">
                <td class="table-content-cell course-detail-cell course-detail-label">Meeting Days:</td>
                <td class="table-content-cell course-detail-cell">
                    <ul>
                        @if ($course->monday)
                            <li>Monday</li>
                        @endif
                        @if ($course->tuesday)
                            <li>Tuesday</li>
                        @endif
                        @if ($course->wednesday)
                            <li>Wednesday</li>
                        @endif
                        @if ($course->thursday)
                            <li>Thursday</li>
                        @endif
                        @if ($course->friday)
                            <li>Friday</li>
                        @endif
                    </ul>
                </td>
            </tr>
        </table>

        <ul class="end">
            <li class="course-detail-label">Instructors:</li>

            @foreach ($course->instructors as $instructor)
                <li>
                    <a href="{{ route('users.show', ['user' => $instructor->id]) }}">{{ $instructor->full_name }}</a>
                </li>
            @endforeach
        </ul>

        <div class="start">
            <a href="{{ route('courses.edit', ['course' => $course->id]) }}" class="btn btn-primary btn-link">Edit Class</a>
        </div>
    </div>

    <table class="table dash-attendance">
        <caption class="table-title">Students</caption>

        <thead>
            <tr class="table-header-row">
                <th class="table-header-cell dash-attendance-first-name">First Name</th>
                <th class="table-header-cell dash-attendance-last-name">Last Name</th>
                <th class="table-header-cell dash-attendance-absences">Absences</th>
                <th class="table-header-cell dash-attendance-tardies">Tardies</th>
                <th class="table-header-cell dash-attendance-on-time">On Time</th>
                <th class="table-header-cell dash-attendance-excused">Excused</th>
                <th class="table-header-cell dash-actions"></th>
            </tr>
        </thead>

        <tbody>
            @if ($course->students->isNotEmpty())
                @foreach ($course->students as $student)
                    <tr class="table-content-row">
                        <td class="table-content-cell dash-attendance-first-name">{{ $student->first_name }}</td>

                        <td class="table-content-cell dash-attendance-last-name">{{ $student->last_name }}</td>

                        <td class="table-content-cell table-number dash-attendance-absences">
                            {{ is_null($student->courseAttendances)
                                ? 0
                                : $student->courseAttendances->where('attendance_status_id', $absentStatusId)->count() }}
                        </td>

                        <td class="table-content-cell table-number dash-attendance-tardies">
                            {{ is_null($student->courseAttendances)
                                ? 0
                                : $student->courseAttendances->where('attendance_status_id', $tardyStatusId)->count() }}
                        </td>

                        <td class="table-content-cell table-number dash-attendance-on-time">
                            {{ is_null($student->courseAttendances)
                                ? 0
                                : $student->courseAttendances->where('attendance_status_id', $presentStatusId)->count() }}
                        </td>

                        <td class="table-content-cell table-number dash-attendance-excused">
                            {{ is_null($student->courseAttendances)
                                ? 0
                                : $student->courseAttendances->where('excused', true)->count() }}
                        </td>

                        <td class="table-content-cell dash-actions">
                            <a href="{{ route('attendances.students.edit', ['course' => $course->id, 'student' => $student->id]) }}" class="btn btn-primary btn-link">Edit Attendance</a>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr class="table-content-row">
                    <td class="table-content-cell" colspan="7">There are no students registered with this class.</td>
                </tr>
            @endif
        </tbody>
    </table>
</div>
@endsection